env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  eqeqeq: [2, always],
  no-console: warn,
  no-restricted-exports: [off],
  import/no-extraneous-dependencies: [error, {devDependencies: true}],
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
}
